### PR TITLE
fixed #157 NPE in TestRunnerViewPart

### LINKED ISSUE #157: NPE in TestRunnerViewPart
We had a [bug report of an NPE from opening the TestRunnerViewPart](https://bugs.eclipse.org/bugs/show_bug.cgi?id=470442).  The stack trace is below.   The NPE is occurring as newSuiteRunInfo() accesses the m_runHistoryAction before it has been configured.

The problem is that TestRunnerViewPart only initializes m_runHistoryAction in configureToolBar(), which is called from createPartControl().  But this updateResultThread() is called as part of the part's init() method.  init() is called before createPartControl(), and in fact it's entirely possible createPartControl() will never be called at all.

!ENTRY org.eclipse.ui 4 4 2015-06-18 15:16:06.921
!MESSAGE Unable to initialize part
!STACK 0
java.lang.NullPointerException
	at org.testng.eclipse.ui.TestRunnerViewPart.newSuiteRunInfo(TestRunnerViewPart.java:418)
	at org.testng.eclipse.ui.TestRunnerViewPart.updateResultThread(TestRunnerViewPart.java:404)
	at org.testng.eclipse.ui.TestRunnerViewPart.init(TestRunnerViewPart.java:219)
	at org.eclipse.ui.internal.ViewReference.initialize(ViewReference.java:140)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:305)

### PR DESCRIPTION
**Pull request by missedone**
fixed #157

### CODE REVIEW

File: testng-eclipse-plugin/src/main/org/testng/eclipse/ui/TestRunnerViewPart.java [hunk 1]
```diff
@@ -229,9 +229,6 @@ public void init(IViewSite site, IMemento memento) throws PartInitException {
     if(progressService != null) {
       progressService.showBusyForFamily(TestRunnerViewPart.FAMILY_RUN);
     }
-
-    // Start the watcher thread, if applicable
-    updateResultThread();
```
Comment (missedone) [inline testng-eclipse-plugin/src/main/org/testng/eclipse/ui/TestRunnerViewPart.java]: both `init(IViewSite site, IMemento memento)` and `createPartControl(Composite parent)` are called when create the viewer part, so let's call `updateResultThread()` once and only after the UI control instantiated.
