### PR TITLE
#344: fixed dependesOnMethods in other package

### LINKED ISSUE #344: The dependonMethod is not work when i dependon a different class method，this issue seems have been fixed in 6.9.9，but now i still have this problem
My eclipse is v4.5
eclipse-testNg 6.11
testNg jar 6.9.10
org.testng.TestNGException: 
com.zhubajie.autotest.announcementservice.TestUpdateAnnouncement.testCase() is depending on method public void com.zhubajie.autotest.announcementservice.TestSaveAnnouncement.testCase(java.util.Map,java.lang.Object), ## **which is not annotated with @Test or not included.**
	at org.testng.internal.MethodHelper.findDependedUponMethods(MethodHelper.java:112)
	at org.testng.internal.MethodHelper.topologicalSort(MethodHelper.java:211)
	at org.testng.internal.MethodHelper.sortMethods(MethodHelper.java:287)
	at org.testng.internal.MethodHelper.collectAndOrderMethods(MethodHelper.java:60)
	at org.testng.TestRunner.initMethods(TestRunner.java:496)
	at org.testng.TestRunner.init(TestRunner.java:247)

### PR DESCRIPTION
**Pull request by missedone**
fixes #344

here is the test case I used:
FooTest and BarTest are in different package, while BarTest.testBar() depends on FooTest.testFoo()

```java
package issue344.bar;

import org.testng.annotations.Test;

public class BarTest {

  @Test(dependsOnMethods="issue344.foo.FooTest.testFoo")
  public void testBar() {
    System.out.println("testing testBar");
  }
}
```

```java
package issue344.foo;

import org.testng.annotations.Test;

public class FooTest {

  @Test
  public void testFoo() {
    System.out.println("testing testFoo");
  }
}
```

this also fixes issue that when right click on the Type, the dependsOnMethods were not collected for test

### CODE REVIEW

File: testng-eclipse-plugin/src/main/org/testng/eclipse/util/LaunchUtil.java [hunk 1]
```diff
@@ -280,7 +280,8 @@ public static void launchMethodConfiguration(IJavaProject javaProject,
         DependencyInfo groupInfo = DependencyInfo.createDependencyInfo(javaProject);
         Set<IMethod> transitiveMethods = findMethodTransitiveClosure(iMethod, groupInfo);
         for (IMethod transitiveMethod : transitiveMethods) {
-          typeAndMethods.add(new TypeAndMethod(iType, transitiveMethod));
+          IType t = transitiveMethod.getDeclaringType();
+          typeAndMethods.add(new TypeAndMethod(t, transitiveMethod));
```
Comment (missedone) [inline testng-eclipse-plugin/src/main/org/testng/eclipse/util/LaunchUtil.java]: use the method's own enclosing type, otherwise, in case of depends on test method in other package, the type would be wrong

**Comment by z475546259** [comment]
I have download the newest eclipse-testng 6.11.1.201707241403 and remove the old  launch configuration before run the test. but when i run the  main test the error occur “，could you help me out， thanks~~
com.zhubajie.autotest.announcementservice.TestUpdateAnnouncement.testCase() is depending on method public void com.zhubajie.autotest.announcementservice.TestSaveAnnouncement.testCase(java.util.Map,java.lang.Object), **# which is not annotated with @Test or not included.**”
is there some setting in eclipse which i didn't set it correcttly？
image
image

**Comment by missedone** [comment]
not sure if you correctly installed the eclipse plugin, please follow the guide [here](http://testng.org/doc/download.html):
>select Help / Install New Software...
Enter the update site URL in "Work with:" field:
Update site for beta: http://beust.org/eclipse-beta
Make sure the check box next to URL is checked and click Next.
Eclipse will then guide you through the process.

now go to "Help -> About" to see if the latest plugin installed
