### PR TITLE
Issue #253, now default log level to '0'

### LINKED ISSUE #253: Run as... default verbose level
### Expected behaviour
The default Verbose Level should be 0.
An "ordinary" developer usually has no use for logging messages more appropriate for a TestNG committer.

### Actual behaviour
The actual verbose level appears to be 2.

### Steps to reproduce
1. Right-click a test class and select "Run as... TestNG Test"
2. Check the Console Tab.
3. It is quite full of logging messages in addition to normal test output.

### Running Configuration
* Plugin Version: 6.9.11

### PR DESCRIPTION
**Pull request by missedone**
fixed #253

### CODE REVIEW

File: testng-eclipse-plugin/src/main/org/testng/eclipse/ui/util/ConfigurationHelper.java [hunk 1]
```diff
@@ -171,36 +171,18 @@ public static String getJvmArgs(ILaunchConfiguration configuration) throws CoreE
 
     addDebugProperties(jvmArgs, configuration);
 
-    switch (ConfigurationHelper.getProtocol(configuration)) {
-    case STRING:
-      jvmArgs.append(" -Dtestng.eclipse.stringprotocol");
```
Comment (missedone) [inline testng-eclipse-plugin/src/main/org/testng/eclipse/ui/util/ConfigurationHelper.java]: this property `testng.eclipse.stringprotocol` is invalid since we pass the `-protocol` arg (rather than system properties) to tell the RemoteTestNG the communication protocol.

File: testng-eclipse-plugin/src/main/org/testng/eclipse/ui/util/ConfigurationHelper.java [hunk 2]
```diff
@@ -171,36 +171,18 @@ public static String getJvmArgs(ILaunchConfiguration configuration) throws CoreE
...
+   * Add the debug and/or verbose properties of RemoteTestNG if user specified
    */
   private static void addDebugProperties(StringBuilder vmArgs, ILaunchConfiguration config) {
-    String[] debugProperties = new String[] {
-        RemoteTestNG.PROPERTY_DEBUG,
-        RemoteTestNG.PROPERTY_VERBOSE
-    };
-    for (String p : debugProperties) {
-      if (System.getProperty(p) != null) {
-        vmArgs.append(" -D").append(p);
```
Comment (missedone) [inline testng-eclipse-plugin/src/main/org/testng/eclipse/ui/util/ConfigurationHelper.java]: let's just simplify this, so that behavior same as what user see on their launch configuration

File: testng-eclipse-plugin/src/main/org/testng/eclipse/ui/util/ConfigurationHelper.java [hunk 3]
```diff
@@ -355,7 +337,7 @@ public static void createBasicConfiguration(IJavaProject javaProject, ILaunchCon
     config.setAttribute(IJavaLaunchConfigurationConstants.ATTR_MAIN_TYPE_NAME,
                         RemoteTestNG.class.getName());
     config.setAttribute(TestNGLaunchConfigurationConstants.TYPE, LaunchType.CLASS.ordinal());
-    config.setAttribute(TestNGLaunchConfigurationConstants.LOG_LEVEL, "2");
+    config.setAttribute(TestNGLaunchConfigurationConstants.LOG_LEVEL, "0"); // default log level for nothing
```
Comment (missedone) [inline testng-eclipse-plugin/src/main/org/testng/eclipse/ui/util/ConfigurationHelper.java]: default log level to `0` for nothing
